language: c

install:
        - sudo bash -c "echo deb http://ppa.launchpad.net/directhex/monoxide/ubuntu precise main >> /etc/apt/sources.list"
        - sudo bash -c "echo deb-src http://ppa.launchpad.net/directhex/monoxide/ubuntu precise main >> /etc/apt/sources.list"
        - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23DC003A
        - sudo apt-get update
        - sudo apt-get install mono-devel mono-gmcs
        - mozroots --import --sync
script:
        - mkdir build
        - cd src
        - mono ./packages/FAKE.3.2.0/tools/FAKE.exe ./build.fsx
        - echo "DONE"            
